// This file was auto-generated by ML.NET Model Builder. 

using System;
using DemoMLNetML.Model;

namespace DemoMLNetML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Col2 = @"Творчеството на Йовков описва по неповторим начин ежедневието на българския селянин, като същевременно разкрива неговите дълбоки надежди и терзания, неговите чисто човешките проблеми. То е свързано също и с различни легенди и предания и с темата за животните и тяхното взаимодействие с човешкия свят. Съдържа следните разкази:- Грехът на Иван Белин- Една торба барут- Граничари- Кошута- Грешница- Едно време- Гълъбът на прозореца- Два врага- Един срещу трима- Друг свят- Дрямката на калмука- Женско сърце- Дивачка- Дядо ДавидЙордан Йовков е един от най-обичаните български писатели. Необикновеният му разказвачески талант му носи прозвището Майстор на късия разказ. Роден е на 9 ноември 1880 година в Жеравна.",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Col1 with predicted Col1 from sample data...\n\n");
            Console.WriteLine($"Col2: {sampleData.Col2}");
            Console.WriteLine($"\n\nPredicted Col1 value {predictionResult.Prediction} \nPredicted Col1 scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
